services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    restart: always
    ports:
      - "5800:5800"
    volumes:
      - "./config:/config:rw"
      - "./downloads:/output:rw"
