services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${LOGIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${LOGIN_PASSWORD}"
    volumes:
      - ./data:/var/lib/pgadmin
